import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Password({ data }) {
  return (
    <>
      <Head>
        <title>Quote</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/new-path/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.description}>
            <h2 className={inter.className}>
              here is your password {data}
            </h2>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://www.dinopass.com/password/simple`);
  const data = await res.text();

  // Pass data to the page via props
  return { props: { data } };
}